Repository chili-study-archive/real-mysql, pull requests merged in 2025-02, with the labels that each got.

#28 [Week6] 영택
  chapter16/taek.md
  chapter17/taek.md
  chapter18/taek.md
Labels: week6

#29 [Week 6] 성언
  chapter16/eony.md
  chapter17/eony.md
  chapter18/eony.md
Labels: week6

#30 [Week 7] 성언
  chapter19/eony.md
  chapter20/eony.md
  chapter21/eony.md
Labels: week7

#31 [Week7] 영택
  chapter19/taek.md
  chapter20/taek.md
  chapter21/taek.md
Labels: week7

#32 [Week8] 영택
  chapter22/taek.md
  chapter23/taek.md
  chapter24/taek.md
Labels: week8

#34 [Week 8] 성언
  chapter22/eony.md
  chapter23/eony.md
  chapter24/eony.md
Labels: week8
